name: Build book and make release

# Only trigger on push and only for frontend files
on:
  
  # Trigger on push to master (edge case, local merge)
  push:
    branches:
      - main
    # tags:
    #   - 'v*'


jobs:
  build:
    name: Compile Book

    runs-on: ubuntu-latest

    steps:

       # Clones repo to the commit that triggered the event
      - name: Cloning repository
        uses: actions/checkout@v3

      # Set up node
      - name: Set up frontend Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: "compiler/.nvmrc"
          cache-dependency-path: "compiler/package-lock.json"
          cache: "npm"

      - name: Install node dependencies
        run: npm i
        working-directory: compiler

      - name: Install cli dependencies
        run: sudo apt install -y ghostscript

      - name: Build book
        run: debug=true npm start
        working-directory: compiler

      - name: Clean up temp files
        run: rm *-{pretoc,toc,content}.pdf
        working-directory: build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/*
